# This workflow will perform a Reshift Javascript scan. 
# TODO: Please make sure to add your token as a secret in project settings.
# The secret name needs to be RESHIFT_TOKEN in this case.

name: Reshift Scan

on:
  push:
    branches: [ main ]


jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install -g @reshiftsecurity/reshift-plugin-npm
    - run: reshift-scan -t ${{ secrets.RESHIFT_TOKEN }}
